spring:
  application:
    name: beautiful-care
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/skincarebeauti
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jakarta:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: create
                create-target: create.sql
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "LGeKsGSd24VeML6rG6EiNGDDBUBDpzR5pkXdT/piWaXmEh8qrvsihcqnmm/NW9ou"

# Cấu hình Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    filter: true

# Cấu hình logging
logging:
  level:
    root: INFO
    com.dailycodework.beautifulcare: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
